site_name: Asabaal Video Utilities
repo_url: https://github.com/asabaal/asabaal-utils
theme:
  name: material
  palette:
    primary: indigo
    accent: amber
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - search.highlight

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_root_heading: true

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Installation: installation.md
  - Quick Start: quickstart.md
  - CLI Reference:
    - Overview: cli/index.md
    - remove-silence: cli/remove-silence.md
    - analyze-transcript: cli/analyze-transcript.md
  - API Reference:
    - Overview: api/index.md
    - Silence Detection: api/silence_detector.md
    - Transcript Analysis: api/transcript_analyzer.md
  - User Guides:
    - Memory Optimization: guides/memory-optimization.md
    - Transcript Enhancement: guides/transcript-enhancement.md
  - Examples:
    - Silence Removal Workflow: examples/silence-removal.md
  - Contributing: contributing.md