"""
Function Flow Renderer for generating control flow visualizations.

This module renders control flow graphs generated by FunctionFlowParser
into interactive HTML visualizations.
"""

import json
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from matplotlib.patches import FancyBboxPatch, Circle
from typing import Dict, List, Any, Optional
from pathlib import Path
try:
    from asabaal_utils.flowscope.function_flow_parser import FunctionFlow, FunctionFlowParser
except ImportError:
    try:
        from .function_flow_parser import FunctionFlow, FunctionFlowParser
    except ImportError:
        from function_flow_parser import FunctionFlow, FunctionFlowParser

# Import dynamic generator with fallback
try:
    from asabaal_utils.flowscope.dynamic_function_flow_generator import generate_dynamic_function_flow
except ImportError:
    try:
        from . import dynamic_function_flow_generator
        generate_dynamic_function_flow = dynamic_function_flow_generator.generate_dynamic_function_flow
    except ImportError:
        try:
            import dynamic_function_flow_generator
            generate_dynamic_function_flow = dynamic_function_flow_generator.generate_dynamic_function_flow
        except ImportError:
            # Fallback: define a stub that raises an informative error
            def generate_dynamic_function_flow(*args, **kwargs):
                raise ImportError("Dynamic function flow generator not available. Install required dependencies or use static rendering.")


class FunctionFlowRenderer:
    """Renders function flow visualizations."""
    
    def __init__(self, output_dir: Path):
        self.output_dir = output_dir
        self.function_flows_dir = output_dir / "function_flows"
        self.function_flows_dir.mkdir(parents=True, exist_ok=True)
    
    def render_function_flow(self, function_flow: FunctionFlow, use_dynamic: bool = True) -> Path:
        """Render a single function flow to HTML."""
        
        if use_dynamic:
            # Use the new dynamic generator
            flow_data = {
                'function_name': function_flow.function_name,
                'module': function_flow.module,
                'file_path': function_flow.file_path,
                'entry_point': function_flow.entry_point,
                'exit_point': function_flow.exit_point,
                'nodes': function_flow.nodes,
                'edges': function_flow.edges
            }
            
            # Create filename
            safe_function_name = function_flow.function_name.replace('.', '_').replace('<', '_').replace('>', '_')
            output_file = self.function_flows_dir / f"{safe_function_name}_flow.html"
            
            generate_dynamic_function_flow(
                flow_data,
                output_file,
                function_name=function_flow.function_name,
                module_name=function_flow.module
            )
        else:
            # Use the old static generator
            html_content = self._generate_function_flow_html(function_flow)
            
            # Create filename
            safe_function_name = function_flow.function_name.replace('.', '_').replace('<', '_').replace('>', '_')
            output_file = self.function_flows_dir / f"{safe_function_name}_flow.html"
            
            with open(output_file, 'w', encoding='utf-8') as f:
                f.write(html_content)
        
        return output_file
    
    def render_module_function_flows(self, module_flows: Dict[str, FunctionFlow], 
                                   module_name: str) -> Path:
        """Render all function flows for a module to a single HTML file."""
        html_content = self._generate_module_flows_html(module_flows, module_name)
        
        safe_module_name = module_name.replace('.', '_')
        output_file = self.function_flows_dir / f"{safe_module_name}_flows.html"
        
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        return output_file
    
    def save_function_flows_json(self, parser: FunctionFlowParser, module_name: str) -> Path:
        """Save function flows data as JSON for loading in visualizations."""
        safe_module_name = module_name.replace('.', '_')
        output_file = self.function_flows_dir / f"{safe_module_name}.json"
        
        # Create data structure for this module
        module_data = {
            'module': module_name,
            'function_flows': {
                name: flow.to_dict() 
                for name, flow in parser.function_flows.items()
            }
        }
        
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(module_data, f, indent=2)
        
        return output_file
    
    def _generate_function_flow_html(self, function_flow: FunctionFlow) -> str:
        """Generate HTML for a single function flow visualization with static image."""
        # Generate static image
        image_filename = f"{function_flow.function_name.replace('.', '_')}_flow.png"
        image_path = self.function_flows_dir / image_filename
        self._create_static_flow_image(function_flow, image_path)
        
        return f"""
<!DOCTYPE html>
<html>
<head>
    <title>Function Flow: {function_flow.function_name}</title>
    <style type="text/css">
        body {{
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f5f5f5;
        }}
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}
        .header {{
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 2px solid #eee;
        }}
        .info {{
            background: #f8f9fa;
            padding: 15px;
            border-radius: 4px;
            margin-bottom: 20px;
        }}
        .flow-image {{
            text-align: center;
            margin: 20px 0;
            border: 1px solid #ddd;
            border-radius: 4px;
            padding: 10px;
            background: #fafafa;
        }}
        .flow-image img {{
            max-width: 100%;
            height: auto;
            border-radius: 4px;
        }}
        .legend {{
            margin-top: 20px;
            padding: 15px;
            background: #f8f9fa;
            border-radius: 4px;
        }}
        .legend-item {{
            display: inline-block;
            margin-right: 20px;
            margin-bottom: 5px;
        }}
        .legend-color {{
            display: inline-block;
            width: 20px;
            height: 20px;
            border-radius: 3px;
            margin-right: 5px;
            vertical-align: middle;
        }}
        .metadata {{
            background: #e9ecef;
            padding: 15px;
            border-radius: 4px;
            margin-top: 20px;
        }}
        .metadata h3 {{
            margin-top: 0;
            color: #495057;
        }}
        .node-list {{
            list-style: none;
            padding: 0;
        }}
        .node-item {{
            background: white;
            margin: 5px 0;
            padding: 10px;
            border-radius: 3px;
            border-left: 4px solid #007bff;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Function Flow Analysis</h1>
            <h2>{function_flow.function_name}</h2>
        </div>
        
        <div class="info">
            <strong>Module:</strong> {function_flow.module}<br>
            <strong>File:</strong> {function_flow.file_path}<br>
            <strong>Control Flow Nodes:</strong> {len(function_flow.nodes)}<br>
            <strong>Edges:</strong> {len(function_flow.edges)}
        </div>
        
        <div class="flow-image">
            <h3>Control Flow Visualization</h3>
            <img src="{image_filename}" alt="Function Flow Diagram" />
        </div>
        
        <div class="legend">
            <strong>Node Types:</strong><br>
            <div class="legend-item">
                <span class="legend-color" style="background: #90ee90;"></span>
                Entry/Exit Points
            </div>
            <div class="legend-item">
                <span class="legend-color" style="background: #ffd700;"></span>
                Assignment
            </div>
            <div class="legend-item">
                <span class="legend-color" style="background: #ffa500;"></span>
                Conditional
            </div>
            <div class="legend-item">
                <span class="legend-color" style="background: #ff9999;"></span>
                Loop
            </div>
            <div class="legend-item">
                <span class="legend-color" style="background: #90ee90;"></span>
                Return
            </div>
            <div class="legend-item">
                <span class="legend-color" style="background: #dda0dd;"></span>
                Try/Except
            </div>
        </div>
        
        <div class="metadata">
            <h3>Flow Sequence</h3>
            <ol class="node-list">
                {self._generate_flow_sequence_html(function_flow)}
            </ol>
        </div>
        
        <div class="metadata">
            <h3>Node Details</h3>
            <div class="node-list">
                {self._generate_node_details_html(function_flow)}
            </div>
        </div>
    </div>
</body>
</html>
        """
    
    def _generate_nodes_js(self, nodes: List) -> str:
        """Generate JavaScript code for nodes."""
        js_lines = []
        for node in nodes:
            # Determine color and shape based on node type
            color_map = {
                'assignment': '#ffd700',  # Gold
                'conditional': '#ffa500',  # Orange
                'loop': '#ff9999',  # Light red
                'return': '#90ee90',  # Light green
                'try': '#dda0dd',  # Plum
                'except': '#f0e68c',  # Khaki
                'merge': '#d3d3d3',  # Light gray
            }
            
            shape_map = {
                'conditional': 'diamond',
                'loop': 'diamond',
                'merge': 'circle',
            }
            
            color = color_map.get(node.type, '#97c2fc')  # Default blue
            shape = shape_map.get(node.type, 'box')  # Default box
            
            # Convert single quotes to double quotes and use JSON encoding
            label_text = str(node.label).replace("\n", "\\n").replace("'", '"') if node.label else ''
            label = json.dumps(label_text, ensure_ascii=False)
            if len(label_text) > 30:
                label = json.dumps(label_text[:27] + '...', ensure_ascii=False)
            
            if node.label:
                label_clean = str(node.label).replace("'", '"')
                title_text = f"{label_clean}\\nLine: {str(node.line)}\\nType: {str(node.type)}"
            else:
                title_text = f"Line: {str(node.line)}\\nType: {str(node.type)}"
            # Use ensure_ascii=False to preserve Unicode characters properly
            title = json.dumps(title_text, ensure_ascii=False)
            
            js_line = f"""{{
                id: '{node.id}',
                label: {label},
                title: {title},
                color: '{color}',
                shape: '{shape}',
                font: {{size: 12}}
            }}"""
            js_lines.append(js_line)
        
        return ',\n            '.join(js_lines)
    
    def _generate_edges_js(self, edges: List[Dict[str, Any]]) -> str:
        """Generate JavaScript code for edges."""
        js_lines = []
        for edge in edges:
            label = edge.get('label', '') or ''
            label_json = json.dumps(str(label))
            js_lines.append(f"""{{
                from: '{edge['from']}',
                to: '{edge['to']}',
                label: {label_json},
                arrows: 'to',
                color: {{color: "#666666"}},
                font: {{size: 10, align: "middle"}}
            }}""")
        
        if not js_lines:
            return ''
        return ',\n            '.join(js_lines)
    
    def _create_static_flow_image(self, function_flow: FunctionFlow, image_path: Path):
        """Create a static PNG image of the function flow."""
        fig, ax = plt.subplots(1, 1, figsize=(12, 8))
        
        # Position nodes in a flow layout
        positions = {}
        level_height = 1.5
        node_spacing = 2.0
        
        # Create hierarchical layout
        node_count = len(function_flow.nodes)
        for i, node in enumerate(function_flow.nodes):
            positions[node.id] = (i % 4 * 2, (i // 4) * 1.5)
        
        # Add entry and exit points
        positions[function_flow.entry_point.id] = (0, 6)
        positions[function_flow.exit_point.id] = (node_count % 4 * 2, (node_count // 4) * 1.5 + 1)
        
        # Draw edges
        for edge in function_flow.edges:
            from_pos = positions[edge['from']]
            to_pos = positions[edge['to']]
            ax.annotate('', xy=to_pos, xytext=from_pos,
                       arrowprops=dict(arrowstyle='->', color='#666666', lw=1.5))
        
        # Draw nodes
        for node in function_flow.nodes:
            pos = positions[node.id]
            color_map = {
                'entry': '#90ee90',
                'exit': '#ff6b6b', 
                'assignment': '#ffd700',
                'conditional': '#ffa500',
                'loop': '#ff9999',
                'return': '#90ee90',
                'try': '#dda0dd'
            }
            color = color_map.get(node.type, '#97c2fc')
            
            # Choose node shape
            if node.type in ['entry', 'exit']:
                circle = Circle(pos, 0.4, color=color, ec='black', linewidth=2, zorder=10)
                ax.add_patch(circle)
            else:
                rect = FancyBboxPatch((pos[0]-0.5, pos[1]-0.3), 1.0, 0.6,
                                     boxstyle="round,pad=0.1", 
                                     facecolor=color, 
                                     edgecolor='black', 
                                     linewidth=1.5,
                                     zorder=10)
                ax.add_patch(rect)
            
            # Add labels
            label = str(node.label)[:20] + '...' if len(str(node.label)) > 20 else str(node.label)
            ax.text(pos[0], pos[1]-0.8, label, 
                    ha='center', va='top', fontsize=8, 
                    bbox=dict(boxstyle='round,pad=0.3', facecolor='white', alpha=0.8))
        
        # Set plot properties
        ax.set_xlim(-1, max(pos[0] for pos in positions.values()) + 1)
        ax.set_ylim(0, max(pos[1] for pos in positions.values()) + 1)
        ax.set_aspect('equal')
        ax.axis('off')
        
        # Add title
        ax.text(len(positions) / 2, max(pos[1] for pos in positions.values()) + 0.5, 
                f'Function Flow: {function_flow.function_name}', 
                ha='center', va='center', fontsize=16, fontweight='bold')
        
        plt.tight_layout()
        plt.savefig(image_path, dpi=150, bbox_inches='tight')
        plt.close()
    
    def _generate_flow_sequence_html(self, function_flow: FunctionFlow) -> str:
        """Generate HTML for flow sequence."""
        sequence_items = []
        for edge in function_flow.edges:
            sequence_items.append(f"<li>{edge['from']} → {edge['to']}</li>")
        return '\n'.join(sequence_items)
    
    def _generate_node_details_html(self, function_flow: FunctionFlow) -> str:
        """Generate HTML for node details."""
        node_items = []
        for node in function_flow.nodes:
            node_items.append(f"""
                <div class="node-item">
                    <strong>{node.id}:</strong> {node.type}<br>
                    <small>{node.label}</small><br>
                    <small>Line {node.line}</small>
                </div>
            """)
        return '\n'.join(node_items)
    
    def _generate_module_flows_html(self, module_flows: Dict[str, FunctionFlow], 
                                  module_name: str) -> str:
        """Generate HTML for all function flows in a module."""
        function_list = []
        for name, flow in module_flows.items():
            safe_name = name.replace('.', '_').replace('<', '_').replace('>', '_')
            function_list.append(f"""
            <div class="function-item">
                <h3><a href="{safe_name}_flow.html" target="_blank">{name}</a></h3>
                <p>
                    <strong>File:</strong> {flow.file_path}<br>
                    <strong>Nodes:</strong> {len(flow.nodes)}<br>
                    <strong>Edges:</strong> {len(flow.edges)}
                </p>
            </div>
            """)
        
        return f"""
<!DOCTYPE html>
<html>
<head>
    <title>Function Flows: {module_name}</title>
    <style type="text/css">
        body {{
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f5f5f5;
        }}
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}
        .header {{
            margin-bottom: 30px;
            padding-bottom: 10px;
            border-bottom: 2px solid #eee;
        }}
        .function-item {{
            margin-bottom: 20px;
            padding: 15px;
            border: 1px solid #ddd;
            border-radius: 4px;
            background: #fafafa;
        }}
        .function-item h3 {{
            margin-top: 0;
            color: #333;
        }}
        .function-item a {{
            text-decoration: none;
            color: #0066cc;
        }}
        .function-item a:hover {{
            text-decoration: underline;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Function Flow Analysis</h1>
            <h2>{module_name}</h2>
            <p>Found {len(module_flows)} functions with control flow analysis</p>
        </div>
        
        {''.join(function_list)}
    </div>
</body>
</html>
"""