"""
Function Flow Renderer for generating dynamic control flow visualizations.

This module renders control flow graphs generated by FunctionFlowParser
into interactive HTML visualizations using the new dynamic system.
"""

import json
from typing import Dict, Any
from pathlib import Path

# Import dynamic generator
try:
    from asabaal_utils.flowscope.dynamic_function_flow_generator import generate_dynamic_function_flow
except ImportError:
    try:
        from . import dynamic_function_flow_generator
        generate_dynamic_function_flow = dynamic_function_flow_generator.generate_dynamic_function_flow
    except ImportError:
        try:
            import dynamic_function_flow_generator
            generate_dynamic_function_flow = dynamic_function_flow_generator.generate_dynamic_function_flow
        except ImportError:
            # Fallback: define a stub that raises an informative error
            def generate_dynamic_function_flow(*args, **kwargs):
                raise ImportError("Dynamic function flow generator not available. Install required dependencies.")


class FunctionFlowRenderer:
    """Renders function flow visualizations using dynamic HTML."""
    
    def __init__(self, output_dir: Path):
        self.output_dir = output_dir
        self.function_flows_dir = output_dir / "function_flows"
        self.function_flows_dir.mkdir(parents=True, exist_ok=True)
    
    def render_function_flow(self, function_flow) -> Path:
        """Render a single function flow to HTML using dynamic visualization."""
        
        # Use new dynamic generator with proper data conversion
        flow_data = function_flow.to_dict()
        
        # Create filename
        safe_function_name = function_flow.function_name.replace('.', '_').replace('<', '_').replace('>', '_')
        output_file = self.function_flows_dir / f"{safe_function_name}_flow.html"
        
        generate_dynamic_function_flow(
            flow_data,
            output_file,
            function_name=function_flow.function_name,
            module_name=function_flow.module
        )
        
        return output_file
    
    def render_module_function_flows(self, module_flows: Dict[str, Any], 
                                   module_name: str) -> Path:
        """Render all function flows for a module to individual HTML files."""
        
        rendered_files = []
        for function_name, function_flow in module_flows.items():
            output_file = self.render_function_flow(function_flow)
            rendered_files.append(output_file)
        
        # Create index file listing all functions
        index_content = self._generate_module_index_html(module_flows, module_name, rendered_files)
        safe_module_name = module_name.replace('.', '_')
        index_file = self.function_flows_dir / f"{safe_module_name}_index.html"
        
        with open(index_file, 'w', encoding='utf-8') as f:
            f.write(index_content)
        
        return index_file
    
    def save_function_flows_json(self, parser, module_name: str) -> Path:
        """Save function flows data as JSON for loading in visualizations."""
        safe_module_name = module_name.replace('.', '_')
        output_file = self.function_flows_dir / f"{safe_module_name}.json"
        
        # Create data structure for this module
        module_data = {
            'module': module_name,
            'function_flows': {
                name: flow.to_dict() 
                for name, flow in parser.function_flows.items()
            }
        }
        
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(module_data, f, indent=2)
        
        return output_file
    
    def _generate_module_index_html(self, module_flows: Dict[str, Any], 
                                  module_name: str, rendered_files: list) -> str:
        """Generate HTML index page for all function flows in a module."""
        function_list = []
        for function_name, function_flow in module_flows.items():
            safe_name = function_name.replace('.', '_').replace('<', '_').replace('>', '_')
            function_list.append(f"""
            <div class="function-item">
                <h3><a href="{safe_name}_flow.html" target="_blank">{function_name}</a></h3>
                <p>
                    <strong>File:</strong> {function_flow.file_path}<br>
                    <strong>Nodes:</strong> {len(function_flow.nodes)}<br>
                    <strong>Edges:</strong> {len(function_flow.edges)}
                </p>
            </div>
            """)
        
        return f"""
<!DOCTYPE html>
<html>
<head>
    <title>Function Flows: {module_name}</title>
    <style type="text/css">
        body {{
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f5f5f5;
        }}
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}
        .header {{
            margin-bottom: 30px;
            padding-bottom: 10px;
            border-bottom: 2px solid #eee;
        }}
        .function-item {{
            margin-bottom: 20px;
            padding: 15px;
            border: 1px solid #ddd;
            border-radius: 4px;
            background: #fafafa;
        }}
        .function-item h3 {{
            margin-top: 0;
            color: #333;
        }}
        .function-item a {{
            text-decoration: none;
            color: #0066cc;
        }}
        .function-item a:hover {{
            text-decoration: underline;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Dynamic Function Flow Analysis</h1>
            <h2>{module_name}</h2>
            <p>Found {len(module_flows)} functions with dynamic control flow analysis</p>
            <p><strong>All function flows use the new interactive dynamic visualization system</strong></p>
        </div>
        
        {''.join(function_list)}
    </div>
</body>
</html>
"""