# ---
# jupyter:
#   jupytext:
#     formats: ipynb,py:percent
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.18.1
#   kernelspec:
#     display_name: Python 3
#     language: python
#     name: python3
# ---

# %% [markdown]
# # Module 10: Build Logic Catalog
#
# ## Overview
# The `build_logic_catalog.py` module is responsible for building a YAML catalog from the aggregated behaviors generated by `aggregate_behaviors.py`. This module transforms the consolidated behavior data into a structured logic catalog that serves as the foundation for prompt generation in Stage 4.
#
# ## Key Functions
# - `build_logic_catalog()` - Main function to create the logic catalog
# - `save_catalog_to_yaml()` - Save the catalog to a YAML file
# - `validate_catalog_structure()` - Validate the catalog format
#
# ## Pipeline Integration
# ```
# Stage 3: aggregate_behaviors.py → Aggregated Behaviors
#     ↓
# Stage 3: build_logic_catalog.py → Logic Catalog (YAML)
#     ↓ 
# Stage 4: generate_prompts.py → Prompt Templates
# ```

# %%
# Import the build_logic_catalog module
import sys
from pathlib import Path
current_dir = Path.cwd()
sys.path.insert(0, str(current_dir))

try:
    from build_logic_catalog import build_catalog
    print("✓ Successfully imported build_catalog from build_logic_catalog")
except ImportError as e:
    print(f"✗ Import failed: {e}")
    print("Note: This module may need to be implemented or import paths fixed")

# %% [markdown]
# ## Function 1: build_catalog()
#
# This is the main function that transforms aggregated behaviors into a structured logic catalog.

# %%
# Let's examine the build_catalog function
import inspect

try:
    source = inspect.getsource(build_catalog)
    print("Function source:")
    print(source)
except:
    print("Function not found - let's check what's available in the module")
    print(dir())

# %% [markdown]
# ## Expected Function Signature
#
# Based on the pipeline design, `build_catalog()` should have this signature:
#
# ```python
# def build_catalog(aggregated_behaviors: dict, output_path: str = None) -> dict:
#     """
#     Build a logic catalog from aggregated behaviors.
#     
#     Args:
#         aggregated_behaviors: Dictionary of aggregated behaviors from aggregate_behaviors.py
#         output_path: Optional path to save the catalog as YAML
#         
#     Returns:
#         Dictionary representing the structured logic catalog
#     """
# ```

# %% [markdown]
# ## Function 2: save_catalog_to_yaml()
#
# This function saves the logic catalog to a YAML file for persistence and sharing.

# %%
# Let's examine the save_catalog_to_yaml function
try:
    from build_logic_catalog import save_catalog_to_yaml
    source = inspect.getsource(save_catalog_to_yaml)
    print("Function source:")
    print(source)
except:
    print("Function not found")

# %% [markdown]
# ## Expected Function Signature
#
# ```python
# def save_catalog_to_yaml(catalog: dict, file_path: str) -> bool:
#     """
#     Save a logic catalog to a YAML file.
#     
#     Args:
#         catalog: The logic catalog dictionary
#         file_path: Path where to save the YAML file
#         
#     Returns:
#         True if successful, False otherwise
#     """
# ```

# %% [markdown]
# ## Function 3: validate_catalog_structure()
#
# This function validates that the catalog follows the expected structure.

# %%
# Let's examine the validate_catalog_structure function
try:
    from build_logic_catalog import validate_catalog_structure
    source = inspect.getsource(validate_catalog_structure)
    print("Function source:")
    print(source)
except:
    print("Function not found")

# %% [markdown]
# ## Expected Function Signature
#
# ```python
# def validate_catalog_structure(catalog: dict) -> tuple[bool, list]:
#     """
#     Validate the structure of a logic catalog.
#     
#     Args:
#         catalog: The logic catalog dictionary to validate
#         
#     Returns:
#         Tuple of (is_valid, error_messages)
#     """
# ```

# %% [markdown]
# ## Expected Logic Catalog Structure
#
# The logic catalog should follow this YAML structure:
#
# ```yaml
# logic_catalog:
#   metadata:
#     version: "1.0"
#     generated_at: "2025-01-XX"
#     source_spec: "path/to/spec.yaml"
#   
#   functions:
#     function_name:
#       signature: "def function_name(args):"
#       description: "Function description from spec"
#       behaviors:
#         - "Behavior 1 from alignment reports"
#         - "Behavior 2 from alignment reports"
#       dependencies:
#         - "other_function_name"
#       complexity: "medium"  # low/medium/high
#       
#   relationships:
#     caller_to_callee:
#       function_name: [called_function_1, called_function_2]
#     data_flow:
#       function_name: 
#         inputs: ["param1", "param2"]
#         outputs: ["return_value"]
# ```

# %% [markdown]
# ## Usage Example
#
# Here's how the module would typically be used in the pipeline:

# %%
# Example usage (pseudo-code since module may not be fully implemented)
example_usage = """
# After aggregate_behaviors.py creates aggregated behaviors
aggregated_behaviors = {
    "functions": {
        "calculate_total": {
            "behaviors": ["Sum all items", "Handle empty list"],
            "dependencies": []
        },
        "apply_tax": {
            "behaviors": ["Calculate tax rate", "Apply to total"],
            "dependencies": ["calculate_total"]
        }
    }
}

# Build the logic catalog
logic_catalog = build_catalog(aggregated_behaviors)

# Validate the catalog
is_valid, errors = validate_catalog_structure(logic_catalog)
if is_valid:
    print("✓ Logic catalog is valid")
else:
    print(f"✗ Validation errors: {errors}")
"""

print(example_usage)

# %% [markdown]
# ## Integration with Pipeline
#
# The `build_logic_catalog.py` module is called by the orchestrator during Stage 3:
#
# 1. **Input**: Aggregated behaviors from `aggregate_behaviors.py`
# 2. **Processing**: Structure behaviors into a catalog format
# 3. **Output**: YAML logic catalog for `generate_prompts.py`
#
# ## Data Flow
#
# ```
# Aggregated Behaviors ──→ build_logic_catalog() ──→ Logic Catalog (dict)
#                                                         │
#                                                         ├──→ validate_catalog_structure()
#                                                         │
#                                                         └──→ save_catalog_to_yaml() ──→ logic_catalog.yaml
# ```

# %% [markdown]
# ## Key Concepts
#
# ### Catalog Organization
# - Groups behaviors by function
# - Maintains dependency relationships
# - Preserves traceability to source spec
#
# ### Structure Validation
# - Ensures required fields are present
# - Validates data types and formats
# - Checks relationship consistency
#
# ### YAML Serialization
# - Human-readable format for inspection
# - Machine-readable for prompt generation
# - Version-controlled for reproducibility

# %% [markdown]
# ## Transformation Process
#
# The module transforms aggregated behaviors into a structured catalog:
#
# ### Input (Aggregated Behaviors)
# ```json
# {
#   "function_name": {
#     "behaviors": ["behavior1", "behavior2"],
#     "source_reports": ["report1.json", "report2.json"]
#   }
# }
# ```
#
# ### Output (Logic Catalog)
# ```yaml
# logic_catalog:
#   functions:
#     function_name:
#       behaviors:
#         - "behavior1"
#         - "behavior2"
#       metadata:
#         source_reports: ["report1.json", "report2.json"]
# ```

# %% [markdown]
# ## Error Handling
#
# The module should handle:
# - Missing or invalid aggregated behaviors
# - Malformed behavior data
# - File I/O errors when saving YAML
# - Validation failures with clear error messages

# %% [markdown]
# ## Testing Considerations
#
# When testing this module:
# - Test with various aggregated behavior formats
# - Verify YAML output is valid and readable
# - Check validation catches structural errors
# - Test error handling for edge cases
#
# See the testing series notebooks for comprehensive test strategies.

# %% [markdown]
# ## Summary
#
# The `build_logic_catalog.py` module is a critical component in Stage 3 of the SpecCoder pipeline:
#
# - **Purpose**: Transform aggregated behaviors into a structured YAML catalog
# - **Key Functions**: build_logic_catalog(), save_catalog_to_yaml(), validate_catalog_structure()
# - **Integration**: Bridges aggregated behaviors to prompt generation
# - **Output**: Structured logic catalog for Stage 4 code generation
#
# This module ensures that behavioral insights are properly organized and validated before being used to generate the final code implementation prompts.
