# ---
# jupyter:
#   jupytext:
#     formats: ipynb,py:percent
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.18.1
#   kernelspec:
#     display_name: Python 3
#     language: python
#     name: python3
# ---

# %% [markdown]
# # Module 11: Generate Prompts
#
# ## Overview
# The `generate_prompts.py` module is responsible for creating per-function prompt templates from the logic catalog generated by `build_logic_catalog.py`. This module transforms the structured catalog into AI-ready prompts that will be used in Stage 4 to generate the final code implementation.
#
# ## Key Functions
# - `generate_function_prompts()` - Create prompts for all functions in the catalog
# - `create_prompt_template()` - Generate a single function prompt template
# - `save_prompts_to_file()` - Save generated prompts to files
#
# ## Pipeline Integration
# ```
# Stage 3: build_logic_catalog.py → Logic Catalog (YAML)
#     ↓
# Stage 4: generate_prompts.py → Prompt Templates
#     ↓ 
# Stage 4: generator.py → Final Code Implementation
# ```

# %%
# Import the generate_prompts module
import sys
from pathlib import Path
current_dir = Path.cwd()
sys.path.insert(0, str(current_dir))

try:
    from generate_prompts import generate_function_prompt
    print("✓ Successfully imported generate_function_prompt from generate_prompts")
except ImportError as e:
    print(f"✗ Import failed: {e}")
    print("Note: This module may need to be implemented or import paths fixed")

# %% [markdown]
# ## Function 1: generate_function_prompts()
#
# This is the main function that creates prompts for all functions in the logic catalog.

# %%
# Let's examine the generate_function_prompts function
import inspect

try:
    source = inspect.getsource(generate_function_prompt)
    print("Function source:")
    print(source)
except:
    print("Function not found - let's check what's available in the module")
    print(dir())

# %% [markdown]
# ## Expected Function Signature
#
# Based on the pipeline design, `generate_function_prompts()` should have this signature:
#
# ```python
# def generate_function_prompts(logic_catalog: dict, output_dir: str = None) -> dict:
#     """
#     Generate prompts for all functions in a logic catalog.
#     
#     Args:
#         logic_catalog: Dictionary representing the logic catalog from build_logic_catalog.py
#         output_dir: Optional directory to save individual prompt files
#         
#     Returns:
#         Dictionary mapping function names to their prompt templates
#     """
# ```

# %% [markdown]
# ## Function 2: create_prompt_template()
#
# This function generates a single prompt template for a specific function.

# %%
# Let's examine the create_prompt_template function
try:
    from generate_prompts import create_prompt_template
    source = inspect.getsource(create_prompt_template)
    print("Function source:")
    print(source)
except:
    print("Function not found")

# %% [markdown]
# ## Expected Function Signature
#
# ```python
# def create_prompt_template(function_name: str, function_data: dict, catalog_context: dict) -> str:
#     """
#     Create a prompt template for a specific function.
#     
#     Args:
#         function_name: Name of the function
#         function_data: Function-specific data from the logic catalog
#         catalog_context: Overall catalog context for dependencies
#         
#     Returns:
#         String containing the formatted prompt template
#     """
# ```

# %% [markdown]
# ## Function 3: save_prompts_to_file()
#
# This function saves the generated prompts to individual files for organization.

# %%
# Let's examine the save_prompts_to_file function
try:
    from generate_prompts import save_prompts_to_file
    source = inspect.getsource(save_prompts_to_file)
    print("Function source:")
    print(source)
except:
    print("Function not found")

# %% [markdown]
# ## Expected Function Signature
#
# ```python
# def save_prompts_to_file(prompts: dict, output_dir: str) -> bool:
#     """
#     Save generated prompts to individual files.
#     
#     Args:
#         prompts: Dictionary mapping function names to prompt templates
#         output_dir: Directory where to save the prompt files
#         
#     Returns:
#         True if successful, False otherwise
#     """
# ```

# %% [markdown]
# ## Expected Prompt Template Structure
#
# Each prompt template should follow this structure:
#
# ```
# You are an expert Python programmer implementing a function based on detailed specifications.
#
# ## Function: {function_name}
#
# ### Signature
# ```python
# {function_signature}
# ```
#
# ### Description
# {function_description}
#
# ### Required Behaviors
# {behaviors_list}
#
# ### Dependencies
# This function may call: {dependencies}
#
# ### Context
# {additional_context_from_catalog}
#
# ### Implementation Requirements
# - Follow Python best practices
# - Include proper error handling
# - Add type hints where appropriate
# - Write clear, maintainable code
#
# Please implement this function according to the specifications above.
# ```

# %% [markdown]
# ## Usage Example
#
# Here's how the module would typically be used in the pipeline:

# %%
# Example usage (pseudo-code since module may not be fully implemented)
example_usage = """
# After build_logic_catalog.py creates the logic catalog
logic_catalog = {
    "functions": {
        "calculate_total": {
            "signature": "def calculate_total(items: list) -> float:",
            "description": "Calculate the total price of all items",
            "behaviors": ["Sum all item prices", "Handle empty list", "Return 0.0 for no items"],
            "dependencies": []
        },
        "apply_tax": {
            "signature": "def apply_tax(total: float, rate: float) -> float:",
            "description": "Apply tax rate to total amount",
            "behaviors": ["Calculate tax amount", "Add to total", "Handle negative rates"],
            "dependencies": ["calculate_total"]
        }
    }
}

# Generate prompts for all functions
from generate_prompts import generate_prompts_index
prompts = generate_prompts_index(
    logic_catalog=logic_catalog,
    output_dir="./stage4_output/prompts/"
)

print(f"Generated {len(prompts)} prompt templates")
for func_name, prompt in prompts.items():
    print(f"✓ Generated prompt for {func_name}")
"""

print(example_usage)

# %% [markdown]
# ## Integration with Pipeline
#
# The `generate_prompts.py` module is called by the orchestrator during Stage 4:
#
# 1. **Input**: Logic catalog from `build_logic_catalog.py`
# 2. **Processing**: Create AI-ready prompt templates for each function
# 3. **Output**: Prompt templates for `generator.py` to use in code generation
#
# ## Data Flow
#
# ```
# Logic Catalog ──→ generate_function_prompts() ──→ Prompts Dictionary
#                                                         │
#                                                         ├──→ create_prompt_template() (per function)
#                                                         │
#                                                         └──→ save_prompts_to_file() ──→ Individual prompt files
# ```

# %% [markdown]
# ## Key Concepts
#
# ### Prompt Engineering
# - Clear, specific instructions for AI code generation
# - Structured format for consistent output
# - Context preservation across function dependencies
#
# ### Template Customization
# - Function-specific context and requirements
# - Dependency information for accurate implementation
# - Behavioral specifications from alignment analysis
#
# ### Output Organization
# - Individual prompt files for modular processing
# - Structured naming convention for easy retrieval
# - Metadata for tracking and debugging

# %% [markdown]
# ## Prompt Template Components
#
# ### 1. Function Identity
# - Function name and signature
# - Clear description of purpose
# - Type hints and parameter information
#
# ### 2. Behavioral Specifications
# - List of required behaviors from alignment reports
# - Edge cases and error conditions
# - Performance considerations
#
# ### 3. Context and Dependencies
# - Related functions that may be called
# - Shared data structures or constants
# - Overall system architecture context
#
# ### 4. Implementation Guidelines
# - Coding standards and best practices
# - Error handling requirements
# - Testing and documentation expectations

# %% [markdown]
# ## Example Generated Prompt
#
# Here's what a generated prompt might look like:

# %%
example_prompt = """
You are an expert Python programmer implementing a function based on detailed specifications.

## Function: calculate_total

### Signature
```python
def calculate_total(items: list) -> float:
```

### Description
Calculate the total price of all items in the shopping cart.

### Required Behaviors
- Sum all item prices in the list
- Handle empty list by returning 0.0
- Validate that items have 'price' attribute
- Raise ValueError for invalid item structures

### Dependencies
This function does not call other functions.

### Context
Part of a shopping cart system. Items are expected to be dictionaries with at least a 'price' key containing numeric values.

### Implementation Requirements
- Follow Python best practices
- Include proper error handling
- Add type hints where appropriate
- Write clear, maintainable code
- Include docstring with examples

Please implement this function according to the specifications above.
"""

print(example_prompt)

# %% [markdown]
# ## File Organization
#
# Generated prompts are typically organized as:
#
# ```
# stage4_output/
# ├── prompts/
# │   ├── calculate_total.prompt
# │   ├── apply_tax.prompt
# │   └── ...
# └── metadata.json  # Contains generation info and function mapping
# ```
#
# Each `.prompt` file contains the complete prompt template for one function.

# %% [markdown]
# ## Error Handling
#
# The module should handle:
# - Missing or invalid logic catalog data
# - Malformed function specifications
# - File I/O errors when saving prompts
# - Template generation failures with clear error messages

# %% [markdown]
# ## Testing Considerations
#
# When testing this module:
# - Test with various logic catalog structures
# - Verify prompt templates are well-formed and complete
# - Check that all required information is included
# - Test file saving and organization
# - Validate prompt effectiveness with actual AI generation
#
# See the testing series notebooks for comprehensive test strategies.

# %% [markdown]
# ## Summary
#
# The `generate_prompts.py` module is a critical component in Stage 4 of the SpecCoder pipeline:
#
# - **Purpose**: Transform logic catalog into AI-ready prompt templates
# - **Key Functions**: generate_function_prompts(), create_prompt_template(), save_prompts_to_file()
# - **Integration**: Bridges structured catalog to final code generation
# - **Output**: Detailed prompt templates for each function
#
# This module ensures that all the behavioral insights and structural information from the previous stages are properly formatted for effective AI code generation, resulting in high-quality, specification-compliant implementations.
